 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.frorm;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import view.frorm.TableauDeBord;

/**
 *
 * @author kakon
 */

public class InterfaceDeConnexion extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceDeConnexion
     */
   
    TableauDeBord dashBordManager=new TableauDeBord();
    TableauDebordSecretaire dashBordsecretaire=new TableauDebordSecretaire();
    
    public InterfaceDeConnexion() {
        initComponents();
        setChangePage();
    }
    
    
    
     private void setChangePage(){
        
       startPage2.getBtnManager().addMouseListener(new java.awt.event.MouseAdapter() {
      
           public void mousePressed(java.awt.event.MouseEvent evt) {
      
              setOnClikBtnManager();
   
           }
 
       });
        startPage2.getBtnSecretaire().addMouseListener(new java.awt.event.MouseAdapter() {
      
           public void mousePressed(java.awt.event.MouseEvent evt) {
      
              setOnClikSecretaire();
   
           }
 
       });
        startPage2.getBtnQuitte().addMouseListener(new java.awt.event.MouseAdapter() {
      
           public void mousePressed(java.awt.event.MouseEvent evt) {
      
              setOnClikBtnQuitte();
   
           }
 
       });



        conPage2.getBtnBack().addMouseListener(new java.awt.event.MouseAdapter() {
      
           public void mousePressed(java.awt.event.MouseEvent evt) {
      
              setOnClikRetour();
   
           }
 
       });
        
         conPage2.getBtnConnexion().addMouseListener(new java.awt.event.MouseAdapter() {
      
           public void mousePressed(java.awt.event.MouseEvent evt) {
      
              setOnClikBtnConnexion();
   
           }
 
       });
        
        
        
        
        
        
        
      
    } 
     private void setOnClikBtnQuitte(){
         System.exit(0);
         
     }
     private void setOnClikSecretaire(){
         
         startPage2.setVisible(false);
         conPage2.setVisible(true);
       // conPage2.getImageConnexion().setIcon(new ImageIcon(getClass().getResource("/icon/petite-fille1.png")));
        conPage2.getImageConnexion().setIcon(new ImageIcon(getClass().getResource("/icon/petite-fille(1).png"),null));
         conPage2.getNameConnexion().setText("Secretaire");
         conPage2.getMatricule().setText("");
         conPage2.getPassword().setText("");
     }
     private void setOnClikBtnManager(){
         startPage2.setVisible(false);
         conPage2.setVisible(true);conPage2.getImageConnexion().setIcon(new ImageIcon(getClass().getResource("/icon/profil2.png")));
         conPage2.getNameConnexion().setText("Manager");
         
         conPage2.getMatricule().setText("");
         conPage2.getPassword().setText("");
     }
     private void setOnClikRetour(){
         
         
         startPage2.setVisible(false);
         conPage2.setVisible(true);
         startPage2.setVisible(true);
         conPage2.setVisible(false);
     }
     
     
     
     
     private void setOnClikBtnConnexion(){
             String matricule=conPage2.getMatricule().getText();
             String password=conPage2.getPassword().getText();
             
         if(conPage2.getNameConnexion().getText().equals("Secretaire")){
             
              if(matricule.equals("5678") && password.equals("secretaire")){
             
                  
                 InterfaceDeConnexion.this.hide();
                 dashBordsecretaire.show();
                 
             }else{
                  
                      JOptionPane.showMessageDialog(getParent(),"CONNEXION IMPOSSIBLE le mot de pass et le matricule ne corespondent pas ");
              }
      
           }else{
                if(matricule.equals("1234") && password.equals("manager")){

                    
                  InterfaceDeConnexion.this.hide();
                   dashBordManager.show();

                   
               }else{

                       JOptionPane.showMessageDialog(getParent(),"CONNEXION IMPOSSIBLE le mot de pass et le matricule ne corespondent pas ");

                } 
         }
       

     }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPage2 = new view.page.StartPage();
        conPage2 = new view.page.ConPage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conPage2, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(startPage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startPage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conPage2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceDeConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceDeConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceDeConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceDeConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceDeConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.page.ConPage conPage2;
    private view.page.StartPage startPage2;
    // End of variables declaration//GEN-END:variables
}
